### ISSUE TITLE
Renaming environment.yaml to environment.yml

### ISSUE THREAD

**Issue by jmoldon** [curso-reproducibilidad-team4/zonificacion-climatica-cte#21]
myBinder utiliza .yml, y parece que no acepta .yaml. A conda le da igual uno que otro, pero mybinder usa ese nombre especificamente.

Ahora ismo cuando carga binder no tiene las dependencias instaladas. Basta con cambiar el nombre del archivo (y la documentación que hace referencia a él).

**Comment by pachi** [comment]
Gracias por la comprobación, @jmoldon
Ahora preparo un commit con los cambios necesarios.
